import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import ConvexClerkProvider from "@/provider/ConvexClerkProvider";
import App from "@/components/shared/App";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/ui/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real Time Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
           attribute="class"
           defaultTheme="system"
           enableSystem
           disableTransitionOnChange
           >
        <ConvexClerkProvider>
          <App><TooltipProvider>{children}</TooltipProvider><Toaster richColors/></App>
        </ConvexClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
